### ISSUE TITLE
I can't install version 1.4.11 on Magento 2.3 with PHP 7.2

### ISSUE THREAD

**Issue by gialampham** [Go-Shippit/Magento2#11]
This problem is by require version of modules on composer.json.
Please update it.
Many thanks  !
![error](https://user-images.githubusercontent.com/38515606/51101050-92510180-180b-11e9-8cee-918023033d58.png)

**Comment by matthew-muscat** [comment]
Hi @gialampham,

We've just released v1.4.14 that adds support for Magento 2.3 (https://github.com/Go-Shippit/Magento2/releases/tag/v1.4.14)

Additionally, confirming that we'll be pushing an update this week to validate support in PHP 7.2

**Comment by matthew-muscat** [comment]
Hi @gialampham  — thanks for reporting this issue

Confirming that release v1.4.15 (https://github.com/Go-Shippit/Magento2/releases/tag/v1.4.15) was made available back in May that addressed this issue. Marking this as resolved / closed.
