### ISSUE TITLE
If using attribute_code with `_` from product the value is always NULL.

### ISSUE THREAD

**Issue by sebastien-kathmandu** [Go-Shippit/Magento2#13]
# If using attribute_code with `_` from product the value is always NULL.

## Step to reproduce.

 - use attribute_code `item_length` for the configuration shippit `shippit/sync_item/product_dimension_length_attribute_code`.
 - create an order
 - create shipment and sync with Shippit

## expected behaviour

We should see the sync order table `shippit_sync_order_item` the field `length` should be filled properly.

## actual behaviour

The field `length` from table `shippit_sync_order_item` is always NULL.

**Comment by matthew-muscat** [comment]
Thanks for the detailed report @sebastien-kathmandu  — confirming we're able to repeat the issue on our end and will have a patch pushed out for this shortly.

**Comment by matthew-muscat** [comment]
@sebastien-kathmandu — thanks again for the report  — confirming that this is now resolved as part of the v1.4.16 release — see https://github.com/Go-Shippit/Magento2/commit/98043047ec860eb3fedfc5ead1cfa831290027ea

**Comment by petitgen** [comment]
Hi @matthew-muscat ,

thanks for your answer,

should we close also the PR I did https://github.com/Go-Shippit/Magento2/pull/14 ?

Thanks again,

**Comment by matthew-muscat** [comment]
@petitgen — have just closed #14 with notes relating to it being fixed in https://github.com/Go-Shippit/Magento2/commit/f03b2f50fbd9cf7558747cd0a4ac8a14577b0bae (and subsequently released as v1.4.16)
