### ISSUE TITLE
Error on shippit configuration page

### ISSUE THREAD

**Issue by realizedev** [Go-Shippit/Magento2#15]
Hi

We are using Magento 2.2.9 with shippit 1.5.3.

When I go to Store > Configuration > Sales > Shippit. This page throws an error. Here is the screenshot: https://i.imgur.com/A29Hljx.jpg

We have reinstalled the extension but still, the same error is showing up on the configuration page.
Although shippit is working fine on the frontend as We can see live shipping quotes coming from shippit on the checkout page.

Can you please guide us through this?

Thanks

**Comment by matthew-muscat** [comment]
Hi @realizedev,

Apologies for not getting back to you sooner with this — this repository is not monitored for support requests.

Looking over the issue briefly — the error thrown looks to be related to a potential problem within the Temando Module, or the way we call out to determine the available shipping methods as part of our "Shipping Method Mapping" options.

If you are still encountering an issue, I'd suggest reaching out to our support team over at support.shippit.com.
