### ISSUE TITLE
shippit_sync_shipments cron job duplicated

### ISSUE THREAD

**Issue by benoitconvert** [Go-Shippit/Magento2#3]
Hi @matthew-muscat 

In [etc/crontab.xml](https://github.com/Go-Shippit/Magento2/blob/master/etc/crontab.xml) the "shippit_sync_shipments" cron job is duplicated.

That leads to the following error during cron execution
`  [Magento\Framework\Exception\LocalizedException]                                                                 
  Invalid Document                                                                                                 
  Element 'job': Duplicate key-sequence ['shippit_sync_shipments'] in unique identity-constraint 'uniqueJobName'.  
  Line: 25    `

FYI we are running on
PHP7.0
Magento 2.2.2

**Comment by matthew-muscat** [comment]
Thanks @benoitconvert,

Confirming that this has been resolved in https://github.com/Go-Shippit/Magento2/commit/7bf6de66dc64a5d76dee0ed995824ec4b9bfb3c4 and available as of v1.4.3
