### ISSUE TITLE
Magento 2.2.x Compatibility

### ISSUE THREAD

**Issue by PivitParkour94** [Go-Shippit/Magento2#5]
I'm trying to get this module to run on Magento 2.2.4 (latest as of writing this).

Installing the module works as expected with a Composer installation and running setup:upgrade, however when trying to access the Shippit section at
`Stores -> Configuration -> Sales -> Shippit`
An error is thrown regarding the `Shippit\Shipping\Logger\Logger` as follows
```
PHP Fatal error: Uncaught TypeError: Argument 3 passed to Shippit\Shipping\Model\Carrier\Shippit::__construct() 
must be an instance of Shippit\Shipping\Logger\Logger, instance of Magento\Framework\Logger\Monolog 
given, called in <magento2>/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php
on line 111 and defined in <magento2>/vendor/shippit/magento2/Model/Carrier/Shippit.php on line 62

```

As this blocks the configuration of the module, it's possible there are other incompatibilities. It would be awesome to get an ETA or a roadmap to see when this is going to be available for Magento 2.2.4 specifically.

Thanks!

**Comment by kabadabra** [comment]
I have the same issue - please can you share a fix or workaround if any? Also on Magento 2.2.4.

**Comment by kabadabra** [comment]
I've done a temporary workaround, not sure if it works 100% yet, but at least I can view shipping panel now.

In /vendor/shippit/magento2/Model/Carrier/Shippit.php  and/vendor/shippit/magento2/Model/Carrier/ClickAndCollect.php change
`\Shippit\Shipping\Logger\Logger $logger`
to
`\Psr\Log\LoggerInterface $logger`

Then in multi/vendor/shippit/magento2/Model/Config/Source/Shipping/Methods.php change the entire toOptionArray() function to

`
public function toOptionArray( $showPlaceholder = false, $excludeShippit = false )
{
    if (!$showPlaceholder) {
        $methods = [[
            'value' => '',
            'label' => '-- Please Select --'
        ]];
    }

    $carriers = $this->_shippingConfig->getAllCarriers();

    foreach ($carriers as $carrierCode => $carrierModel) {
        $carrierMethods = $carrierModel->getAllowedMethods();

        // if the carrier is shippit, exclude
        // it from the returned results
        if ($excludeShippit && ($carrierCode == 'shippit' || $carrierCode == 'shippit_cc')
            ) {
            continue;
        }

        if ($carrierMethods) {
            $carrierTitle = $this->_scopeConfig->getValue(
	            'carriers/' . $carrierCode . '/title',
	            ScopeInterface::SCOPE_STORE
            );

            $methods[ $carrierCode ] = [ 'label' => $carrierTitle, 'value' => [] ];

            foreach ( $carrierMethods as $methodCode => $methodTitle ) {
                $displayMethodTitle = '';
	            if ($methodTitle instanceof Phrase) {
		            $displayMethodTitle = $methodTitle->getText();
	            }

	            $methods[ $carrierCode ][ 'value' ][] = [
		            'value' => $carrierCode . '_' . $methodCode,
		            'label' => '[' . $carrierCode . '] ' . $displayMethodTitle,
	            ];
            }
        }
    }

    return $methods;
}
`

**Comment by matthew-muscat** [comment]
@PivitParkour94 thanks for reporting this issue — i can confirm that our latest module release (v1.4.4) should resolve this issue.

This issue specifically affects Magento v2.2.4, due to what appears to be some changes in the logger / di implementation. (see https://github.com/magento/magento2/issues/14950).

The changes specifically relating to this issue can be found in https://github.com/Go-Shippit/Magento2/commit/c60a2ab3d17ffdaea0be6109dc6fdd94acdb6816

**Comment by kabadabra** [comment]
Thanks @matthew-muscat - I can confirm it's working this side 👍 
Thanks for the prompt fix!

**Comment by PivitParkour94** [comment]
Too easy @matthew-muscat, this is working fine on 2.2.4.

Thanks for your work man.
