### ISSUE TITLE
Checkout issue on v1.4.4

### ISSUE THREAD

**Issue by kabadabra** [Go-Shippit/Magento2#6]
Hi there, using the v1.4.4 release on Magento 2.2.4 we are getting the following error on checking out:

```
"Fatal Error: 'Uncaught Error: Call to a member function getShippitAuthorityToLeave() on null in \/data\/web\/magento2\/vendor\/shippit\/magento2\/Plugin\/Checkout\/QuoteAuthorityToLeavePlugin.php:58\nStack trace:\n#0 \/data\/web\/magento2\/vendor\/magento\/framework\/Interception\/Interceptor.php(121): Shippit\\Shipping\\Plugin\\Checkout\\QuoteAuthorityToLeavePlugin->beforeSaveAddressInformation(Object(Magento\\Checkout\\Model\\ShippingInformationManagement\\Interceptor), 104664, Object(Magento\\Checkout\\Model\\ShippingInformation))\n#1 \/data\/web\/magento2\/app\/code\/WeltPixel\/GoogleTagManager\/Plugin\/ShippingInformation.php(53): Magento\\Checkout\\Model\\ShippingInformationManagement\\Interceptor->Magento\\Framework\\Interception\\{closure}(104664, Object(Magento\\Checkout\\Model\\ShippingInformation))\n#2 \/data\/web\/magento2\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): WeltPixel\\GoogleTagManager\\Plugin\\ShippingInformation->aroundSaveAddressInformation(Object(Magento\\Checkout\\Model\\ShippingInformationManagement\\Interceptor), Object(Closure), 104664, Ob' in '\/data\/web\/magento2\/vendor\/shippit\/magento2\/Plugin\/Checkout\/QuoteAuthorityToLeavePlugin.php' on line 58"
```

Screenshot of checkout error: https://cl.ly/0W1i1x0w2V2m/Image%202018-06-22%20at%2012.32.35.png

Console error shown: https://cl.ly/0p2m1C3F3B3c/Image%202018-06-22%20at%2012.33.14.png

Know what might be causing this issue?

**Comment by matthew-muscat** [comment]
Hi @kabadabra  — thanks for reporting this.

Confirming we've just released v1.4.5 that should resolve this  — we introduced some additional checks when processing the quote details for ATL + Delivery Instructions (see https://github.com/Go-Shippit/Magento2/commit/db16d4a629315290b1564d09525b63dc9dbfff37).

v1.4.5 should resolve the checkout error — i would suggest confirming though that you are seeing ATL + Delivery Instructions being applied to the order and sent to shippit after this update.
