### ISSUE TITLE
System Config Shipping Methods Don't Load When Product Collection Empty

### ISSUE THREAD

**Issue by PivitParkour94** [Go-Shippit/Magento2#8]
Tested on version 1.4.7

When trying to access the shipping methods in the system config for a brand new Magento 2.2.5 installation, I am getting a completely blank screen, when not in developer mode.

Changing to developer mode meant I could diagnose the issue and found that we need to define the productArray before iterating the product collection. 

I will create a pull request with this change, but wanted to explain the issue here.

Thanks.

**Comment by matthew-muscat** [comment]
Thanks for raising this @PivitParkour94 — confirming that we've applied your change in `develop` (655939c98601ba4e54427b4a54bc1c7f55edcb6c) and it'll be included in the next release due out by the end of the week.
